# Generated by Django 5.2 on 2025-05-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
